In [2]:
import pandas as pd
from pandasql import sqldf

In [ ]:
#source venv/Scripts/activate  -> aktivacija virtual environmenta!!!!!!

In [3]:
df=pd.read_csv(r"C:\Users\bnadj\Desktop\Python_GitHub\Working-with-databases\car_data.csv")
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [7]:
sqldf("SELECT Year, COUNT(Year) FROM df GROUP BY Year ORDER BY COUNT(Year) DESC")

    Year  COUNT(Year)
0   2015           61
1   2016           50
2   2014           38
3   2017           35
4   2013           33
5   2012           23
6   2011           19
7   2010           15
8   2008            7
9   2009            6
10  2006            4
11  2005            4
12  2007            2
13  2003            2
14  2018            1
15  2004            1

In [6]:
sqldf("SELECT Car_name, Present_Price, Year FROM df WHERE Year>2015")

         Car_Name  Present_Price  Year
0            ciaz           9.85  2017
1   vitara brezza           9.83  2018
2            ciaz           8.89  2016
3        alto 800           3.60  2017
4          ertiga          10.79  2016
..            ...            ...   ...
81           city          13.60  2016
82           jazz           8.40  2016
83           city          11.60  2016
84           city          12.50  2017
85           brio           5.90  2016

[86 rows x 3 columns]

In [8]:
sqldf("SELECT DISTINCT Seller_Type FROM df")

  Seller_Type
0      Dealer
1  Individual

In [9]:
sqldf("SELECT Seller_Type, SUM(Present_Price) FROM df GROUP BY Seller_Type")

  Seller_Type  SUM(Present_Price)
0      Dealer             2122.83
1  Individual              173.34

In [11]:
sqldf("SELECT Fuel_Type, SUM(Kms_Driven) as total_kms FROM df GROUP BY Fuel_Type ORDER BY SUM(Kms_Driven) DESC")

  Fuel_Type  total_kms
0    Petrol    8013416
1    Diesel    3022195
2       CNG      85498

In [29]:
customers_data = {
    "CustomerID": [1, 2, 3, 4, 5],
    "Name": ["Ana", "Marko", "Ivana", "Luka", "Petra"],
    "City": ["Zagreb", "Split", "Rijeka", "Osijek", "Pula"]
}
customers_df = pd.DataFrame(customers_data)
customers_df

   CustomerID   Name    City
0           1    Ana  Zagreb
1           2  Marko   Split
2           3  Ivana  Rijeka
3           4   Luka  Osijek
4           5  Petra    Pula

In [30]:
orders_data = {
    "OrderID": [101, 102, 103, 104, 105, 106],
    "CustomerID": [1, 2, 1, 3, 5, 2],  
    "Product": ["Laptop", "Mouse", "Monitor", "Keyboard", "Laptop", "Tablet"],
    "Quantity": [1, 2, 1, 1, 1, 3],
    "OrderDate": ["2026-01-01", "2026-01-03", "2026-01-05", "2026-01-06", "2026-01-07", "2026-01-08"]
}
orders_df = pd.DataFrame(orders_data)
orders_df

   OrderID  CustomerID   Product  Quantity   OrderDate
0      101           1    Laptop         1  2026-01-01
1      102           2     Mouse         2  2026-01-03
2      103           1   Monitor         1  2026-01-05
3      104           3  Keyboard         1  2026-01-06
4      105           5    Laptop         1  2026-01-07
5      106           2    Tablet         3  2026-01-08

In [ ]:
products_data = {
    "ProductID": [1, 2, 3, 4, 5],
    "Product": ["Laptop", "Mouse", "Monitor", "Keyboard", "Tablet"],
    "Price": [800, 20, 150, 50, 300],
    "SupplierID": [1, 2, 1, 3, None]  
}
products_df = pd.DataFrame(products_data)
products_df

   ProductID   Product  Price  SupplierID
0          1    Laptop    800         1.0
1          2     Mouse     20         2.0
2          3   Monitor    150         1.0
3          4  Keyboard     50         3.0
4          5    Tablet    300         NaN

In [32]:
suppliers_data = {
    "SupplierID": [1, 2, 3, 4],
    "SupplierName": ["TechCorp", "GadgetWorld", "KeyboardsInc", "TabletsRUs"],
    "Country": ["Germany", "USA", "China", "Japan"]
}
suppliers_df = pd.DataFrame(suppliers_data)
suppliers_df

   SupplierID  SupplierName  Country
0           1      TechCorp  Germany
1           2   GadgetWorld      USA
2           3  KeyboardsInc    China
3           4    TabletsRUs    Japan

Kupci koji su napravili barem jednu narudžbu

In [33]:
sqldf("SELECT c.Name FROM customers_df c JOIN orders_df o ON c.CustomerID=o.CustomerID")

    Name
0    Ana
1    Ana
2  Marko
3  Marko
4  Ivana
5  Petra

Prikaži sve narudžbe zajedno s cijenom proizvoda

In [35]:
sqldf("SELECT o.Product, SUM(o.Quantity*p.Price) FROM orders_df o JOIN products_df p ON o.Product=p.Product GROUP BY p.Product")

    Product  SUM(o.Quantity*p.Price)
0  Keyboard                       50
1    Laptop                     1600
2   Monitor                      150
3     Mouse                       40
4    Tablet                      900

Pronađi ukupnu količinu naručenih proizvoda po kupcu

In [36]:
sqldf("SELECT c.Name, SUM(o.Quantity) FROM customers_df c JOIN orders_df o ON c.CustomerID=o.CustomerID GROUP BY c.Name")

    Name  SUM(o.Quantity)
0    Ana                2
1  Ivana                1
2  Marko                5
3  Petra                1

Prikaži sve narudžbe zajedno s cijenom proizvoda i ukupnom vrijednošću narudžbe

In [38]:
sqldf("SELECT o.Product, p.Price,  SUM(o.Quantity*p.Price) AS total FROM orders_df o JOIN products_df p ON o.Product=p.Product GROUP BY o.Product")

    Product  Price  total
0  Keyboard     50     50
1    Laptop    800   1600
2   Monitor    150    150
3     Mouse     20     40
4    Tablet    300    900

Prikaži proizvode koji su naručeni više od jednom

In [39]:
sqldf("SELECT o.Product FROM orders_df o JOIN products_df p ON o.Product=p.Product WHERE o.Quantity>1")

  Product
0   Mouse
1  Tablet

Prikaži sve kupce koji nikada nisu naručili Tablet

In [49]:
sqldf("SELECT Name FROM customers_df WHERE Name NOT IN (SELECT c.Name FROM customers_df c JOIN orders_df o ON c.CustomerID=o.CustomerID WHERE o.Product='Tablet')")

    Name
0    Ana
1  Ivana
2   Luka
3  Petra