In [2]:
import pandas as pd
from pandasql import sqldf

In [ ]:
#source venv/Scripts/activate  -> aktivacija virtual environmenta!!!!!!

In [3]:
df=pd.read_csv(r"C:\Users\bnadj\Desktop\Python_GitHub\Working-with-databases\car_data.csv")
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [7]:
sqldf("SELECT Year, COUNT(Year) FROM df GROUP BY Year ORDER BY COUNT(Year) DESC")

    Year  COUNT(Year)
0   2015           61
1   2016           50
2   2014           38
3   2017           35
4   2013           33
5   2012           23
6   2011           19
7   2010           15
8   2008            7
9   2009            6
10  2006            4
11  2005            4
12  2007            2
13  2003            2
14  2018            1
15  2004            1

In [6]:
sqldf("SELECT Car_name, Present_Price, Year FROM df WHERE Year>2015")

         Car_Name  Present_Price  Year
0            ciaz           9.85  2017
1   vitara brezza           9.83  2018
2            ciaz           8.89  2016
3        alto 800           3.60  2017
4          ertiga          10.79  2016
..            ...            ...   ...
81           city          13.60  2016
82           jazz           8.40  2016
83           city          11.60  2016
84           city          12.50  2017
85           brio           5.90  2016

[86 rows x 3 columns]