In [1]:
import sqlite3 
import pandas as pd

In [20]:
conn=sqlite3.connect('database2.db')
# # stvara novu (praznu) bazu podataka u istom folderu gdje se nalazi .ipnby skripta

In [3]:
customers_data = {
    "CustomerID": [1, 2, 3, 4, 5],
    "Name": ["Ana", "Marko", "Ivana", "Luka", "Petra"],
    "City": ["Zagreb", "Split", "Rijeka", "Osijek", "Pula"]
}
customers_df = pd.DataFrame(customers_data)
customers_df.to_sql("customers",conn,index=False)

5

In [ ]:
# def query(db:str,sql_query:str):
#     """Funkcija koja kreira SQL upit za bazu podataka db"""
#     try:
#         conn=sqlite3.connect(db)
#         cursor=conn.cursor()
#         result=cursor.execute(sql_query).fetchall()
#         conn.close()
#     except Exception as e:
#         print(e)
#     else:
#         return result

In [28]:
def read_only_query(db:str,sql_query:str) -> pd.DataFrame | None:
    """Funkcija koja kreira SQL upit za bazu podataka db. Ako se funkcija uspjesno izvrsi output je pd.DataFrame, a inace None."""
    try:
        with sqlite3.connect(db) as conn:
            return pd.read_sql(sql_query,conn)
    except Exception as e:
        print(e)
        return None

In [29]:
read_only_query("database2.db","SELECT * FROM customers")

   CustomerID   Name    City
0           1    Ana  Zagreb
1           2  Marko   Split
2           3  Ivana  Rijeka
3           4   Luka  Osijek
4           5  Petra    Pula
5           6  Petar  Rijeka
6           7  Jakov   Split

In [30]:
read_only_query("database2.db","SELECT Name,City FROM customers WHERE City LIKE 'Z%'")

  Name    City
0  Ana  Zagreb

In [31]:
read_only_query("database2.db","SELECT Name, City FROM customers WHERE Name LIKE 'P_%'")

    Name    City
0  Petra    Pula
1  Petar  Rijeka

Prilikom korištenja: INSERT, UPDATE i DELETE naredbi uvijek je na kraju potrebna naredba conn.commit()

In [26]:
cursor=conn.cursor()
cursor.execute("INSERT INTO customers(CustomerID,Name,City) VALUES (?,?,?)",(7,"Jakov","Split"))
conn.commit()